### ISSUE TITLE
Question - annular rings

### ISSUE THREAD

**Issue by mengstr** [TechPaula/DCJ11Hack-#1]
Hey Paula, inspired by some DCJ11 projects I just bought one off eBay and while waiting for it to arrive (and then probably even longer before I actually will make something with it ^__^) I look into the projects a bit closer.  

I noticed that you're using 0.3/0.45 vias here - isn't that an awfully narrow annular ring? Just about half of what the usual cheap Chinese fabs recommend. Do you use something better than them or are you just relying on luck here? If it works for you I might adopt that size in tight spots as well...

**Comment by TechPaula** [comment]
I get my PCBs from JLCPCB, never had a problem with this and I've been using JLCPCB for around 6 years.
I do try and avoid this where I can, but sometimes it's not possible.
